server:
  port: 8082

spring:
    datasource:
      url: jdbc:mysql://14.215.104.99:6307/hive
      username: dm_admin
      password: Zar7kYNl
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
